### ISSUE TITLE
HNNW: Standaard taal is Engels --> Nederlands

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#106]
(Nieuwe) bezoekers zien de website "by default' in het Engels.
Voor HNNW graag aanpassen naar standaard Nederlands.

Wanneer een gebruiker voor de eerste keer inlogt op HNNW is de website in het Engels.
Dit graag aanpassen naar standaard Nederlands op HNNW.

**Comment by 0x029Ax0** [comment]
Fixed.

**Comment by 0x029Ax0** [comment]
Zie dat er een aantal strings ontbreken in de huidige nederlandse vertalingen waardoor ze terugvallen op engels. Fix ik vanavond nog.

**Comment by 0x029Ax0** [comment]
Fixed.
