### ISSUE TITLE
Server: BETA - HSTS-policy 

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#111]
Browsers onthouden HSTS per (sub-)domein. Het niet toevoegen van HSTS voor ieder (sub-)domein (in een redirect-keten) kan gebruikers kwetsbaar maken voor MITM-aanvallen. Om die reden testen we HSTS bij het eerste contact, d.w.z. voordat een eventuele doorverwijzing plaatsvindt.

HSTS dwingt af dat een webbrowser direct via HTTPS verbindt bij terugkerend bezoek. Dit helpt man-in-the-middle-aanvallen te voorkomen. Een HSTS-geldigheidsduur (max-age) van tenminste zes maanden achten we voldoende veilig. Een lange geldigheidsduur heeft als voordeel dat ook infrequente bezoekers beschermd zijn. Het nadeel is dat wanneer je wil stoppen met HTTPS, je langer moet wachten totdat de geldigheid van de HSTS-policy in alle browsers die je website bezochten, is verlopen.

bron: https://internet.nl/site/beta.hnnw.nl/875738/#control-panel-10

**Comment by 0x029Ax0** [comment]
Fixed
