### ISSUE TITLE
Server: BETA - TLS 1.0 en TLS 1.1 uitfaseren.

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#112]
Webserver ondersteunt TLS-versies die je weloverwogen dient uit te faseren, omdat bekend is dat deze fragiel zijn en het risico lopen in de toekomst onvoldoende veilig te worden.

bron: https://internet.nl/site/beta.hnnw.nl/875738/#control-panel-11

**Comment by 0x029Ax0** [comment]
Fixed.
