### ISSUE TITLE
Server: BETA - Ciphers

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#113]
Webserver ondersteunt een of meer ciphers die de status uit te faseren hebben omdat bekend is dat deze fragiel zijn en het risico lopen in de toekomst onvoldoende veilig te worden.

bron: https://internet.nl/site/beta.hnnw.nl/875738/#control-panel-12

**Comment by 0x029Ax0** [comment]
Fixed.
