### ISSUE TITLE
Server: BETA - HTTP security headers aanpassen

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#116]
Security header configuraties aanpassen:

- [x] X-Frame-Options
- [x] X-Content-Type-Options
- [x] X-XSS-Protection
- [x] Content-Security-Policy (CSP)
- [x] Referrer-Policy aanwezigheid

bron: https://internet.nl/site/beta.hnnw.nl/875738/#control-panel-27

**Comment by 0x029Ax0** [comment]
Fixed.
