### ISSUE TITLE
Zoeken: Tags - Error handling [tag not found]

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#119]
Wanneer men gaat zoeken naar niet bestaande tags via:  /zoeken/tags/x
verschijnt een rode balk met "tags.not_found"

Dit label aanpassen naar  "tag niet gevonden"
Rode balk mag verdwijnen.

**Comment by 0x029Ax0** [comment]
Fixed.
