### ISSUE TITLE
Defacing kruimelpad

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#12]
Als ik "inloggen" of "registreren" aanklik dan krijg ik een extra balk boven mijn kruimelpad te zien (defacing van de website) waarbij het kruimelpad er onder wordt getoond. Vervolgens verdwijnt het weer en blijft het juiste kruimelpad zichtbaar.

**Comment by 0x029Ax0** [comment]
Zelfde probleem als: https://github.com/SSC-ICT-Innovatie/HNNW-project/issues/15

Closed for now.
