### ISSUE TITLE
/projecten/starten - verplichte velden: rode waarschuwingsteksten

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#120]
Wanneer men een verplicht veld niet invult komt hier een rode waarschuwingstekst bij te staan.
Een aantal op het projectformulier zijn niet correct:

Projectomschrijving: "Description nl is verplicht."
Ministerie: "Ministry id bestaat niet."

**Comment by 0x029Ax0** [comment]
Fixed.
