### ISSUE TITLE
werkpakketten/toevoegen - verplichte velden: rode waarschuwingsteksten

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#121]
Wanneer men een verplicht veld niet invult komt hier een rode waarschuwingstekst bij te staan.
Een aantal op het werkpakketformulier zijn niet correct:

Title nl is verplicht.
Description nl is verplicht.
Description en is verplicht.
Task category is verplicht.

**Comment by 0x029Ax0** [comment]
Fixed.
