### ISSUE TITLE
Nieuwe groep aanmaken / Header afbeelding geeft 500 error

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#122]

**Comment by 0x029Ax0** [comment]
Deze kan ik niet reproduceren op mijn lokale omgeving en ook online ziet dit er bij mij wel goed uit. Zou je een screenshot kunnen posten?

**Comment by cookiemonster** [comment]
De error is nu verdwenen maar het uploaden van een nieuwe afbeelding lukt nog niet,

**Comment by 0x029Ax0** [comment]
Opgelost als het goed is.
