### ISSUE TITLE
Profiel: Aanstellingen - toevoegen werkt niet

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#123]
Van uit **/profiel/updaten** is het niet mogelijk om een aanstelling op te slaan.
Ook wanneer alle velden zijn ingevuld.

**Comment by 0x029Ax0** [comment]
Heb net 2 andere bugs opgelost (header image & tags) maar deze kan ik niet reproduceren. Kan zowel op lokale als beta omgeving aanstellingen toevoegen, updaten of verwijderen.

Zou je hem nog eens willen checken?

**Comment by cookiemonster** [comment]
Het is nu mogelijk om een aanstelling toe te voegen, updaten en verwijderen.

Is het mogelijk om het veld **Afdeling** toe te voegen?
Kan het veld ook **Locactie** ook drop-down combobox worden?

**Comment by 0x029Ax0** [comment]
Is afdeling niet hetzelfde als departement? 
Ik zal de locatie aanpassen naar een combobox.

**Comment by cookiemonster** [comment]
Van boven naar beneden:

* Ministerie
* ~~Directoraten~~
* (Uitvoerings)organisatie
* ~~Clusters/Peilers/Kolomen~~
* Afdelingen
* ~~Teams~~

Voor HNNW gebruiken we 

- Ministerie / Organisatie
- Afdeling

Teams kan men zelf aanmaken als een groep onder **community/groepen**

Zie ook het [organigram van BZK](https://www.rijksoverheid.nl/ministeries/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/documenten/publicaties/2018/10/19/organogram-ministerie-van-bzk).

**Comment by 0x029Ax0** [comment]
![afbeelding](https://user-images.githubusercontent.com/17317618/83130895-50162080-a0df-11ea-9a82-a22a0836b489.png)

**Comment by 0x029Ax0** [comment]
Werkt momenteel; alleen de afdeling wordt niet geladen wanneer je klaar bent met de "create". Na een refresh werkt het wel. Ik krijg de preload niet werkend, dus ga het hele ding herschrijven denk ik. Tijdelijke bugfix.
