### ISSUE TITLE
Registratie: BETA omgeving laat gebruikersregistratie toe zonder geldig rijksoverheid emailadres

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#125]
Het is mogelijk om een nieuwe account te registreren met een niet Rijksoverheid emailadres.
Alleen goedgekeurde domeinen mogen gebruikt worden om een account registreren op HNNW.

Zie ook #88  Admin: Registratie - Toegestaan Domeinen Lijst

**Comment by 0x029Ax0** [comment]
Dat kwam omdat het uitstond, nu ik het heb aangezet werkt het wel alleen de flash message ontbreekt wanneer je een ongeldig email adres gebruikt.

**Comment by 0x029Ax0** [comment]
Opgelost; zet het zo live.
