### ISSUE TITLE
accepteren aanmelding scherm blijft staan

### ISSUE THREAD

**Issue by ramonfiedler** [SSC-ICT-Innovatie/HNNW-project#127]
Dit scherm blijft staan en verdwijnt niet na accepeteren
![Schermafbeelding 2020-05-26 om 12 46 54](https://user-images.githubusercontent.com/42998678/82892195-56759280-9f4f-11ea-9f2d-7dcefad321a3.png)

**Comment by 0x029Ax0** [comment]
Opgelost!
