### ISSUE TITLE
Defacing footer links

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#13]
Bij het aanklikken van "links" in de footer wordt de pagina opnieuw geladen, waarbij defacing optreed. Tekst wordt kleiner (ander font?) en verspringt.

**Comment by 0x029Ax0** [comment]
Zelfde probleem als issue: https://github.com/SSC-ICT-Innovatie/HNNW-project/issues/15

Closed for now.
