### ISSUE TITLE
Wachtwoord vergeten: email

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#131]
Wachtwoord vergeten email word niet verzonden? 
Deze komt niet aan.

**Comment by 0x029Ax0** [comment]
Dat is mij inderdaad ook opgevallen. Het lijkt erop dat geen enkele email aankomt. Zou je de smtp gegevens willen controleren? Aangezien emails het eerder wel deden en er niks is veranderd aan onze kant.

**Comment by cookiemonster** [comment]
Status update 28 mei 2020:
Tijdelijke workaround via Google mail services.
Email van Nederlandse ISP beland in de spamfolder.
Onderzoek naar oorzaak loopt.
