### ISSUE TITLE
Copy op pagina 'wachtwoord resetten' klopt niet

### ISSUE THREAD

**Issue by pgteekens** [SSC-ICT-Innovatie/HNNW-project#134]
Bij het resetten van m'n wachtwoord kom ik bij het kopiëren van de reset-link naar mijn browser (Firefox onder DWR Next) op een pagina waarbij de captions van de velden niet juist worden ingevuld. Er staat wel een verwijzing, maar de beoogde tekst verschijnt niet. Je ziet dus als bezoeker deze verwijzingen in beeld:

@('auth_reset_password_form_email')
@('auth_reset_password_form_code')
@('auth_reset_password_form_password')
@('auth_reset_password_form_password_confirmation')
@('auth_reset_password_form_back')
@('auth_reset_password_form_submit')

**Comment by pgteekens** [comment]
<img width="779" alt="DWR-Next-v1803 2020-06-02 15-37-38" src="https://user-images.githubusercontent.com/62380632/83530328-dcfc1800-a4eb-11ea-9930-c4b5bd3d4121.png">

**Comment by 0x029Ax0** [comment]
Opgelost
