### ISSUE TITLE
Nieuwe groep aanmaken resulteert foutmelding

### ISSUE THREAD

**Issue by pgteekens** [SSC-ICT-Innovatie/HNNW-project#135]
**Gebruikte browsers**: Firefox via DWR Next, Safari via OSX

**Reproductiepad:**
- maak een nieuwe groep aan
- noem 'm "Gebruikerspanel SSC-ICT"
- vul alle tekstvelden met minimaal 1 karakter
- kies 1 tag "samenwerken"
- geen actie voor het veld 'header' 
- klik op "Opslaan"

Resultaat: white screen met 500 | Error (zie bijlage)
<img width="1294" alt="DWR-Next-v1803 2020-06-02 16-18-22" src="https://user-images.githubusercontent.com/62380632/83531070-cb674000-a4ec-11ea-9399-67dfa6e0ef62.png">

**Comment by 0x029Ax0** [comment]
Opgelost.

**Comment by pgteekens** [comment]
Bij het benaderen van de groep ‘SSC-ICT Gebruikerspanel’ krijg ik toch weer dezelfde foutmelding. Een andere groep aanmaken (volgens het reproductiepad in dit issue) levert hetzelfde resultaat (500 error)

**Comment by pgteekens** [comment]
Kun je dit issue opnieuw openen, of moet ik een nieuw exemplaar aanmaken @VerheijenWebdevelopment ?

**Comment by 0x029Ax0** [comment]
Opnieuw geopend, ik ga het controleren.

**Comment by 0x029Ax0** [comment]
Volgens mij heb ik het probleem opgelost nu.

**Comment by pgteekens** [comment]
Haha, dat is snel! Ik ga het even checken.

**Comment by pgteekens** [comment]
Ziet er goed uit, Nick! Ik ga verder verkennen en straks wat proefcontent neerzetten voor het panel.

**Comment by 0x029Ax0** [comment]
Top! Als er nog dingen zijn hoor ik het graag, ga ik ze vandaag nog proberen op te lossen. Sluit ik de issue voor nu :)
