### ISSUE TITLE
Project aanmaken werkt niet op in de test en productie omgeving

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#136]
Een nieuw project aanmaken werkt niet op in de test opmgeving: 500 error
Productie omgeving geeft geen error maar redirtect naar de homepage en maakt geen project aan.

Project invoer _Plekchecker Reloaded_ data staat [hier](https://c.rijksconnect.nl/group/ssc-ict-innovatie?msg=58DaTNmfmG5Wzd2qM)

**Comment by 0x029Ax0** [comment]
Bugfix staat live, volgens mij is het nu opgelost. Verwijderen even het project dat ik met je data heb aangemaakt en probeer het zelf ook om te verifiëren dat het nu is opgelost.
