### ISSUE TITLE
Meld nu je project aan

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#14]
Als ik nog niet ben ingelogd en ik klik in de donker blauwe vlak op de tekst “meld nu je project aan”, dan linkt deze naar “boven” (herladen van de pagina).

Ik zou verwachten dat de website ziet dat ik nog niet ben ingelogd en dat hij aan me vraagt om in te loggen.

**Comment by 0x029Ax0** [comment]
Klopt, ik had een link naar # gedaan ipv naar een echte pagina. Opgelost in eerdere ticket.
