### ISSUE TITLE
Wijzigingen project wordt niet opgeslagen

### ISSUE THREAD

**Issue by ramonfiedler** [SSC-ICT-Innovatie/HNNW-project#144]
Bij het aanmaken van een nieuw 
![Schermafbeelding 2020-06-10 om 10 38 29](https://user-images.githubusercontent.com/42998678/84247042-ccf5c100-ab07-11ea-9000-18d8d117cc3d.png)
project verdwijnen alle gegevens nadat ik wijzigingen project het gedaan. Ook in mijn profiel komt het project niet terug. zie de screenshots
![Schermafbeelding 2020-06-10 om 10 39 59](https://user-images.githubusercontent.com/42998678/84246944-a3d53080-ab07-11ea-8bc9-87d79f708365.png)
![Schermafbeelding 2020-06-10 om 10 39 15](https://user-images.githubusercontent.com/42998678/84247016-c23b2c00-ab07-11ea-8a2d-67c94dc97c7a.png)

**Comment by 0x029Ax0** [comment]
Heb de boosdoener gevonden; dit was het gevolg van 1 van de security policies die we op de beta omgeving hadden ingesteld. De regels zijn nu wat versoepeld en formulier validatie zou weer moeten werken naar verwachting.

Ondertussen gaan we zoeken naar een oplossing die zowel veilig als goed werkt. Closed voor nu, mocht er nog iets anders zijn graag een nieuwe issue aanmaken. Thanks!
