### ISSUE TITLE
vriend uitnodigen geeft 500 error 

### ISSUE THREAD

**Issue by ramonfiedler** [SSC-ICT-Innovatie/HNNW-project#145]
![Schermafbeelding 2020-06-11 om 09 57 40](https://user-images.githubusercontent.com/42998678/84360220-0e4ea500-abca-11ea-8332-42b16637a48d.png)
![Schermafbeelding 2020-06-11 om 09 56 39](https://user-images.githubusercontent.com/42998678/84360246-160e4980-abca-11ea-8157-cf69498cfbb2.png)

**Comment by ramonfiedler** [comment]
update nu is het wel gelukt, ik zie  geen error meer

**Comment by 0x029Ax0** [comment]
Top, dan sluit ik hem!
