### ISSUE TITLE
N2W knop links boven

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#15]
Als ik van taal wissel dan verkleint de tekst in de N2W knop even, springt omhoog en komt vervolgens in de juiste grootte en op de juiste plaats terug (defacing van de website).

**Comment by 0x029Ax0** [comment]
Defacing van een website is wel iets heftiger. Het klopt dat de CSS af en toe later ingeladen wordt. Dit heeft te maken met vue die nog moet laden op de pagina, ben op zoek naar een oplossing hiervoor.

**Comment by 0x029Ax0** [comment]
Duplicate van https://github.com/SSC-ICT-Innovatie/HNNW-project/issues/31, closing for now.
