### ISSUE TITLE
Poll geeft 500-error bij openen

### ISSUE THREAD

**Issue by pgteekens** [SSC-ICT-Innovatie/HNNW-project#152]
Collega Irina Zijlstra heeft onderstaande poll aangemaakt:

https://beta.hnnw.nl/community/polls/eerste-indruk

Als ik als gebruiker (en eigenaar van deze groep) deze poll kies volgt een white screen met 500-foutmelding.

**Comment by cookiemonster** [comment]
Issue is opgelost.
