### ISSUE TITLE
Foutmelding bij wachtwoord vergeten

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#16]
![Screenshot 2020-03-08 at 09 45 42](https://user-images.githubusercontent.com/11490452/76258302-9764e180-6253-11ea-8e8a-f69d9de98602.png)
![Screenshot 2020-03-08 at 09 46 26](https://user-images.githubusercontent.com/11490452/76258316-9df35900-6253-11ea-88c9-e168a92fba82.png)

Symfony component debug exception fatalthrowable error
class sendacoountrecoveryemailnotfound

**Comment by 0x029Ax0** [comment]
Opgelost in volgende update.
