### ISSUE TITLE
Nieuw project starten: issues bij invoeren gegevens

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#161]
Feedback van BETA test gebruiker 18

"1. Veld Categorie: zelf tekst invullen lijkt mogelijk, maar bij Opslaan wijzigingen, gebeurt er niks. Later 1 vd waarden geselecteerd.
2. GUI: na opslaan Wijzigingen niet opvallend duidelijk waar foutieve invoer zit. Bleek dat Engels invoer in Omschrijving ook verplicht was. Tekst was heel klein, als gebruiker moet je dus van top tot teen goed screenen. Kan gebruikersvriendelijker.
3. Sommige ingevulde gegevens worden niet opgeslagen, terug naar init situatie (leeg). Bij lege startdatum, en klikken op Opslaan wijzigingen, resulteerde dit in 500 Server error. Klikken op Pagina terug."

**Comment by ramonfiedler** [comment]
Yo de label invalid?

**Comment by cookiemonster** [comment]
Issue zal in de volgende release worden opgelost.
