### ISSUE TITLE
Dashboard - Consistent taalgebruik

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#17]
Het taalgebruik in het dashboard is niet consistent.

Ik ben in het nederlands ingelogd en er staan engelse termen zoals bijvoorbeeld:
Reputation  points, tasks completed, projects completed, etc.

**Comment by 0x029Ax0** [comment]
Alles vertaald naar het nederlands op "feed" na. Denk dat deze blijft. Voor nu gesloten.
