### ISSUE TITLE
Dashboard - Vriendelijkheid

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#18]
Persoonlijk zou ik het fijn vinden om een melding te krijgen die gerelateerd is met de huidige tijd.

Nu staat er neutraal “goedendag”

Wat ik veracht is op basis van de systeem tijd van de grbuiker.
Goedemorgen / goedemiddag / goedeavond

**Comment by 0x029Ax0** [comment]
veranderd naar:
```
    "greeting_morning" => "Goedemorgen :name!",
    "greeting_afternoon" => "Goedemiddag :name!",
    "greeting_evening" => "Goedenavond :name!",
    "greeting_night" => "Goedenacht :name!",
```

Online met volgende update.
