### ISSUE TITLE
Profiel - Anders dan verwacht profiel mogelijkheden

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#19]
Als ik op mijn eigen naam klik dan krijg ik een rij met opties.
Waaronder:
Mijn profiel => List functie (wat staat er nu)
en
Profiel aanpassen => Pas profiel aan

Wat ik zou verwachten is:
Als ik mijn profiel zou willen aanpassen is dat ik naar mijn profiel ga en daar vervolgens de opties krijg om eventueel zaken aan te passen.

**Comment by 0x029Ax0** [comment]
Kan nu via beide wegen. Of is de suggestie om de link uit het dropdown menu voor de gebruiker weg te halen?

**Comment by WinkoErades** [comment]
Je hebt nu beiden, ik zou verwachten 1 ingang die logisch is.

**Comment by 0x029Ax0** [comment]
Design sprint

**Comment by 0x029Ax0** [comment]
Bij nader inzien, kan net zo goed weg uit het hoofdmenu. Ook  met oog op verdere uitbreiding wellicht  slim om het zo minimalistisch mogelijk te houden. Kortom; verwijderd uit hoofdmenu en nu enkel via de profiel pagina te bereiken.
