### ISSUE TITLE
Zoekveld (op homepage): autocomplete functionaliteit

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#2]
* Niet geauthenticeerde gebruiker
  * Bekende zoektermen

* Geauthenticeerde gebruiker
 * Laatste zoekopdrachten

**Comment by 0x029Ax0** [comment]
Lijkt incompleet; bekende zoektermen voor guests. En waar wordt naar gezocht voor authenticated users?

- Laatste zoekopdrachten
- Bekende zoektermen

Even nadenken hoe bovenstaande subfeatures gerealiseerd kunnen worden.
