### ISSUE TITLE
Profiel - aanpassen broodkruimel

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#20]
![Screenshot 2020-03-08 at 10 20 43](https://user-images.githubusercontent.com/11490452/76258185-62588f00-6253-11ea-95a4-51a94fa0b67f.png)
Werking anders dan verwacht.

Als ik mijn profiel wil wijzigen, kom ik op mijn profiel pagina.
Wat ik niet verwacht is dat de broodkruimel mij laat zien dat ik in de Ledenlijst sta:
Home > Ledenlijst > Profiel van winko erades > Update profiel

Wat ik wel verwacht is:
Home > Profiel van winko erades > Update profiel

**Comment by 0x029Ax0** [comment]
Opgelost in volgende update.
