### ISSUE TITLE
Profiel - Niet uploaden profielfoto

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#21]
![Screenshot 2020-03-08 at 10 18 13](https://user-images.githubusercontent.com/11490452/76258108-3ccb8580-6253-11ea-913a-aab4b19b3ad0.png)
Hoewel profielfoto gekozen/geselecteerd kan worden, wordt deze niet ingeladen.
Ook niet na de optie wijzigingen opslaan.

**Comment by 0x029Ax0** [comment]
Lokaal opgelost, zal dit testen zodra de nieuwe versie online staat

**Comment by 0x029Ax0** [comment]
Opgelost.

Het probleem is dat de directories opnieuw geplaatst worden met elke update en daarmee hun permissions verlliezen. Oplossing is om na elke update de volgende commando's uit te voeren:
```
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```

Closed o7

**Comment by WinkoErades** [comment]
Dus dan hebben we een apart script nodig om na het compileren de boel recht te zetten mbt permissies?

**Comment by 0x029Ax0** [comment]
Ja.

We gebruiken momenteel een zogenaamde "bare" git repository. Vervolgens als we een commit naar de server pushen zal die bare repo alle bestanden in de juiste directory plaatsen en daarmee de update uitvoeren. Dit gebeurd door command die in de post-hook van de git repo wordt gedefinieerd. Daar zouden we, in theorie, ook commands moeten kunnen neerzetten die permissies rechtzetten. Dat heb ik geprobeerd maar dat werkte niet naar wens dus heb ik het even gelaten voor wat het nu is.

Dus of we moeten uitzoeken hoe we dat alsnog werkend kunnen krijgen of wanneer we een ci/cd gaan opzetten moet het daarin worden opgenomen. Waarschijnlijk handig om dit op een staging server te testen en niet op productieserver.
