### ISSUE TITLE
Profiel - Onjuiste werking profiel aanpassen e-mailadres

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#24]
Onjuiste werking Profiel aanpassen e-mailadres

Als ik mijn profiel aanpas en ik verander daarbij mijn E-mailadres, dan wordt deze niet gematched op  eventueel bestaande  E-mailadressen.

Ik had een account winko@abc.123.
Ik ben ingelogd onder winko@xyx.xyz
Ik mag in mijn profiel update mijn e-mailadres wijzigen van winko@xyz.xyz naar winko@abc.123.

**Comment by 0x029Ax0** [comment]
Scherp. Opgelost in volgende update.
