### ISSUE TITLE
Projecten - Foutmelding aanmaken project

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#25]
Foutmelding aanmaken project 

Ingevuld: 
Titel: Koekjes bakken
Slogan: Wie bakt de lekkerste koekjes om mijn team te motiveren
Beschrijving: Om mijn team te motiveren wil graag de lekkerste koekjes voor bij de koffie
Header achtergrond plaatje: No file selected 
Product categorie: hardware 
Werkmethode: kanban
Project Status: open
Start op: 8-3
Eindigt op: 13-3

Na opnieuw proberen blijkt dat Header achtergrond plaatje geen invloed heeft op het resultaat
![Screenshot 2020-03-08 at 12 09 31](https://user-images.githubusercontent.com/11490452/76256939-07259d00-6251-11ea-9890-da51c4cf807a.png)
![Screenshot 2020-03-08 at 12 09 44](https://user-images.githubusercontent.com/11490452/76256941-0987f700-6251-11ea-9131-efad5b1c70dc.png)

**Comment by 0x029Ax0** [comment]
Denk dat deze error is opgelost, zal hem proberen te reproduceren wanneer de laatste versie online staat.
