### ISSUE TITLE
Projecten - Werking verplichte velden

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#26]
![Screenshot 2020-03-08 at 11 56 20](https://user-images.githubusercontent.com/11490452/76257980-fd049e00-6252-11ea-94fb-c94a3b62614f.png)
Andere werking dan verwacht.

Ik had verwacht dat verplichte velden een bepaalde aanduiding zouden hebben als zijnde verplicht in te vullen.

**Comment by 0x029Ax0** [comment]
Dat ze rood worden is in dit geval de aanduiding. Er zit waarschijnlijk een filosofie achter, zal er eens naar kijken (Vuetify is het framework en dat is volgens mij op Material design gebaseerd). Suggesties zijn welkom in ieder geval, zie niet zo 1,2,3 een betere versie hiervan.

**Comment by WinkoErades** [comment]
Rood is achteraf, * is vooraf...

**Comment by 0x029Ax0** [comment]
Dus * toevoegen aan verplichte velden ter aanduiding dat ze verplicht zijn. Roger dodger.

**Comment by 0x029Ax0** [comment]
Fixed
