### ISSUE TITLE
Projecten - Foutmelding na het bijwerken en opslaan van de verplichte velden

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#27]
![Screenshot 2020-03-08 at 12 00 33](https://user-images.githubusercontent.com/11490452/76257097-52d84680-6251-11ea-881e-80e92f13159a.png)
Foutmelding na het bijwerken en opslaan van de verplichte velden

Na het bijwerken van de verplichte velden Project categorie en werkmethode krijg ik een foutmelding na het “Opslaan”.

**Comment by 0x029Ax0** [comment]
Gefixed in volgende update
