### ISSUE TITLE
Werkpakketten - Ontbrekend test werkpakket

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#28]
Ontbrekend test werkpakket programmeren in progress

**Comment by 0x029Ax0** [comment]
Dus je wilt een dummy werkpakket entry; die in progress als status heeft; en programmeren als categorie. Alle werkpakketten worden nu randomly generated wanneer de database geseed wordt, dus dat kan kloppen. Is geen issue verder denk ik dus closed.
