### ISSUE TITLE
Werkpakketten - Consistent taalgebruik werkpakketten

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#29]
Het taalgebruik in het werkpakketten overzicht is niet consistent.

Ik ben in het nederlands ingelogd en er staan engelse termen zoals bijvoorbeeld:
skills, completed, open, in progress, etc.

**Comment by 0x029Ax0** [comment]
"skills" is veranderd naar "vaardigheden".

**Comment by 0x029Ax0** [comment]
De status van een werkpakket is model-gedreven, oftewel komt uit de database, en de waardes hiervan zijn nog niet te vertalen en engels is de default. De default taal gaat niet veranderen maar het integreren van een package die vertalingen van model waardes mogelijk maakt staat wel op de backlog.

Closed voor nu.
