### ISSUE TITLE
Registratie formulier: localization [veld:aanhef]: NL

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#3]

**Comment by 0x029Ax0** [comment]
Bedoel je hiermee dat mensen hun preferred locale aan kunnen geven bij registratie? En dat het dus vervolgens in de database / edit profiel bijgehouden wordt?

**Comment by cookiemonster** [comment]
Registratie formulier is nu het Nederlands. Issue kan gesloten worden.
