### ISSUE TITLE
Algemeen - Verspringende styling van ui elementen

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#31]
Defacing pagina jumps

De webpagina verspringt als gebruik wordt gemaakt van de optie: 
[<] [1] [2] [3] [>]

**Comment by 0x029Ax0** [comment]
Wat bedoel je hier precies mee? Wil je dat hij automatisch naar boven scrolled als je gebruik maakt van de pagination? Dat staat namelijk op de backlog al, zal ik naar voren schuiven dan.

**Comment by WinkoErades** [comment]
Op het moment dat ik de pagination gebruik, springt deze weg en verplaatst zich deze. Ik ben niet technisch maar het lijkt alsof er eerst de ene opmaak staat en daarna de volgende er overheen komt ofzo, waardoor het verspringt.

**Comment by 0x029Ax0** [comment]
Dit is een issue die op alle elementen invloed heeft en dit heeft me Vue te maken. Die laadt een aantal ms later dan de rest van de pagina (want javascript laadt pas in als de html is gerendered). Research vereist om dit op te lossen.
