### ISSUE TITLE
Werkpakketten - Verwachting menu items

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#32]
Bij de menu items links, zoals bij senioriteiten, tijdsbestek, etc. zou ik verwachten dat er een korte toelichting bij zou staan.
Zoals bijvoorbeeld:
Benodigde senioriteit, Verwachtte taak duur

**Comment by 0x029Ax0** [comment]
Kan je deze teksten aanleveren per kopje? Kopjes zijn:

- Status
- Categorieen
- Skills
- Senioriteit (andere naam hiervoor zie andere ticket)
- Tijdsbestek

**Comment by 0x029Ax0** [comment]
Info tooltip bij overview sidemenu headers toegevoegd aan backlog

**Comment by WinkoErades** [comment]
Design sprint!
