### ISSUE TITLE
Werkpakketten - Senioriteiten taalkundig onjuist

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#33]
Senioriteiten is taalkundig onjuist.

**Comment by 0x029Ax0** [comment]
Wat is het alternatief dan?

**Comment by WinkoErades** [comment]
Ja ook geen flauw idee...  Iets voor in een design sprint wellicht?!

**Comment by cookiemonster** [comment]
Gaarne "Vereiste senioriteit" naar *Ervaringsniveau*

**Comment by 0x029Ax0** [comment]
Fixed.
