### ISSUE TITLE
Werkpakketten - Bijzondere werking Senioriteiten filter 1

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#38]
De keuze van senioriteiten beïnvloed de result-set op een merkwaardige manier, namelijk lege paginas met jump opties:
[<] [1] [2] [>]
![Screenshot 2020-03-08 at 11 27 26](https://user-images.githubusercontent.com/11490452/76257718-8798cd80-6252-11ea-8d64-250fe202bfba.png)

**Comment by 0x029Ax0** [comment]
Kan ik lokaal niet reproduceren, waarschijnlijk al gefixed tijdens het ontwikkelen.
