### ISSUE TITLE
Werkpakketten - Werking werkpakket dashboard

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#40]
Taken en werkpakketten

Als ik mij inschijft op een taak/werkpakket dan kan ik deze op afgerond zetten en mij vervolgens uitschrijven.

De status van het pakket in de werkpakketten lijst blijft echter op open staan?

En is nergens in mijn dashboard te zien als zijnde?

**Comment by 0x029Ax0** [comment]
Status wordt geupdate in volgende update.

- Duidelijkere weergave van openstaande/voltooide werkpakketten in dashboard opgenomen in backlog
- Automatisch uitschrijven wanneer werkpakket is voltooid toegevoegd aan backlog
