### ISSUE TITLE
proffiel / vaardigheden: tessify-core::profiles.profile_skill_no_skills

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#42]
1. login
2. bezoek profiel een gebruiker zonder skills

Zie Ondervaardigheiden
tessify-core::profiles.profile_skill_no_skills

Verwaching: "Nog geen skills toegevoegd"

**Comment by 0x029Ax0** [comment]
Fixed in next update.
