### ISSUE TITLE
Profiel:  Reputatie - foutmelding bij geen reputatie

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#44]
Op een profiel waar nog geen reputatie punten zijn verdiend is de button *BEKIJK REPUTATIE GESCHIEDENIS" zichtbaar. Wanneer de gebruiker hier klikt komt er een klein popup scherm met de volgende melding: "tessify-core::profile.profile_reputation_history_dialog_no_transactions"

Graag button  *BEKIJK REPUTATIE GESCHIEDENIS" niet zichtbaar maken als er geen data is.

**Comment by 0x029Ax0** [comment]
Fixed in next update.
