### ISSUE TITLE
werkpakket: hic-ipsam-quam

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#48]
Er staat: "X & Y werken zijn hiermee aan de slag" 
Graag aanpassen naar "X & Y zijn hiermee aan de slag."

**Comment by 0x029Ax0** [comment]
Zal in plaats daarvan de tekst volledig dynamisch maken en X en Y vervangen met de daadwerkelijke namen van de mensen die er op dat moment aan werken.

**Comment by cookiemonster** [comment]
Ja dat is wat ik bedoelde :-)  👍
