### ISSUE TITLE
Werkpakket:  Subscribe button en SCHRIJF MIJ IN button

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#49]
In bv werkpakket _illum-aut-omnis-qui-qui_ zie je een SUBSCRIBE button boven en een SCHRIJF MIJ IN button beneden.

Verwachting dat beiden buttons gelijk zijn. Oplossing verwijder de bovenste button.

**Comment by 0x029Ax0** [comment]
Ben het niet eens met de oplossing, want dan zou de subscribe/volg functionaliteit wegvallen. Lijkt mij een goede voor de design sprint; hoe kunnen we de opties (en in dit geval vooral de verschillende stadia waarin een werkpakket zich kan bevinden) het beste weergeven.

**Comment by 0x029Ax0** [comment]
Subscribe is veranderd naar volgen en minder obvious gemaakt, helpt hopelijk voor deze issue.

**Comment by 0x029Ax0** [comment]
Zelf maar geclosed..
