### ISSUE TITLE
projecten starten / toevoegen: URL vs Breadcrumb path en titel

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#50]
Vanaf de projecten pagina drukt men op de **Project starten** button.
De gebruiker land op pagina Project starten zichtbaar in het Breadcrumb pad en de (pagina) titel echter de url is **/projecten/toevoegen**

**Comment by 0x029Ax0** [comment]
Fixed in volgende update.
