### ISSUE TITLE
Projecten - Aanmaken resources - Textueel anders dan verwacht

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#58]
Er staat aanstelling toevoegen, terwijl ik resources wil toevoegen, dat is anders dan dat ik verwacht.
![Screenshot 2020-04-06 at 09 27 32](https://user-images.githubusercontent.com/11490452/78537111-3f3be380-77ef-11ea-9541-24cd280af854.png)

**Comment by 0x029Ax0** [comment]
Hele component vertaald waarmee het probleem is opgelost (in de volgende update).
