### ISSUE TITLE
Projecten - Opslaan van projecten - Button

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#59]
De knop / bijbehorende text is erg klein / summier. Hierdoor was ik zoekende naar waar ik moest drukken om het op te slaan.
![Screenshot 2020-04-06 at 09 30 36](https://user-images.githubusercontent.com/11490452/78537334-a22d7a80-77ef-11ea-91a1-1b2b33de37bd.png)

**Comment by 0x029Ax0** [comment]
Opgelost in de volgende update.
