### ISSUE TITLE
Projecten - Opslaan van projecten - Button locatie

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#60]
Graag een uniforme plek voor de opslag knop (onderin / bovenin / of beide), het zit nu ergen waar ik het niet verwacht.
![Screenshot 2020-04-06 at 09 30 36](https://user-images.githubusercontent.com/11490452/78537456-cf7a2880-77ef-11ea-9dde-709989d05c5b.png)

**Comment by 0x029Ax0** [comment]
De uniforme plek is rechtsonder. In dit geval is dat een beetje ongelukkig omdat de rechter kolom veel korter is dan de linker kolom waardoor de knop halverwege komt.

Heb de button groter gemaakt en de tekst die ontbrak toegevoegd. Ik vind hem nu duidelijk genoeg, ben je het daarmee eens? (online met volgende update).

**Comment by 0x029Ax0** [comment]
Zelf maar geclosed.
