### ISSUE TITLE
Projecten - Bekijken van projecten

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#61]
Om te wijzigen moet ik het knopje "open" klikken, ik verwacht dan een knopje "wijzigen" (of Edit) of zoiets.
![Screenshot 2020-04-06 at 09 32 09](https://user-images.githubusercontent.com/11490452/78537650-1700b480-77f0-11ea-9e9d-16674f4ba6da.png)

**Comment by ramonfiedler** [comment]
De indruk die gewekt wordt is dat je bij dit scherm nog zelf additionele rollen handmatig kan toevoegen wat niet zo is, 
<img width="995" alt="Schermafbeelding 2020-04-07 om 11 50 18" src="https://user-images.githubusercontent.com/42998678/78655408-41bd3c80-78c6-11ea-9e19-0e3b31a72674.png">

**Comment by 0x029Ax0** [comment]
> 
> 
> Om te wijzigen moet ik het knopje "open" klikken, ik verwacht dan een knopje "wijzigen" (of Edit) of zoiets.
> ![Screenshot 2020-04-06 at 09 32 09](https://user-images.githubusercontent.com/11490452/78537650-1700b480-77f0-11ea-9e9d-16674f4ba6da.png)

Ik volg deze niet helemaal. Het labeltje "open" is zelf niet interactief en duidt enkel de status aan. Als je een project wilt aanpassen zul je eerst naar de view-project pagina moeten gaan en als je dan de eigenaar bent vindt je daar een edit knop.



> 
> 
> De indruk die gewekt wordt is dat je bij dit scherm nog zelf additionele rollen handmatig kan toevoegen wat niet zo is,
> <img alt="Schermafbeelding 2020-04-07 om 11 50 18" width="995" src="https://user-images.githubusercontent.com/42998678/78655408-41bd3c80-78c6-11ea-9e19-0e3b31a72674.png">

Ook deze volg ik niet. Er staat heel groot "aanmelden voor project" en je moet een rol selecteren. Hoe de verwachting ontstaat dat je zelf nog een rol kan bedenken op dat moment snap ik niet helemaal. Wat zou een oplossing hiervoor zijn? Duidelijker aangeven dat het gaat om een rol selecteren i.p.v. toevoegen?

**Comment by 0x029Ax0** [comment]
P.S. @ramonfiedler misschien handiger om de volgende keer een aparte issue aan te maken; nu is het een double post. Maakt verder niet uit, top om te zien dat je het hier nu plaatst i.p.v. op de chat 👍
