### ISSUE TITLE
Projecten - Bekijken van projecten Object-Object

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#62]
Het was mij ten tijde van niet opgevallen, maar de screenshot liet mij iets zien... Namelijk in het zwarte deel bij de project titel staat [object:Object]
![Screenshot 2020-04-06 at 09 32 09](https://user-images.githubusercontent.com/11490452/78537836-5f1fd700-77f0-11ea-8176-b4db9ba4b076.png)
.

**Comment by 0x029Ax0** [comment]
Kan deze niet reproduceren op mijn lokale omgeving. Ik zie dat het een project is dat je zelf hebt toegevoegd; welke stappen heb je genomen om tot dit resultaat te komen?
