### ISSUE TITLE
Profiel aanpassen - Foto's

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#63]
Na het selecteren van de verschillende foto's update het profiel / achtergron plaatje niet naar de gekozen foto's. Ik zou verwachten dat dit wel gebeurt. Opdat je kan zien welke foto je geselecteerd hebt. Het wijzigen gebeurt pas na het opslaan.
![Screenshot 2020-04-06 at 09 50 31](https://user-images.githubusercontent.com/11490452/78538000-a0b08200-77f0-11ea-8efe-fcbd807af0be.png)

**Comment by ramonfiedler** [comment]
ik heb dat nog een keer getest afgelopen weekend, maar het werkt nog niet

**Comment by 0x029Ax0** [comment]
Zowel avatar als header achtergrond worden, met ingang van volgende update, via de API direct geupload en geupdate zodra er een nieuwe afbeelding wordt geselecteerd.
