### ISSUE TITLE
Aanmaken werkpakketten

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#64]
Na het opslaan / aanmaken van een werkpakket, krijg ik een scherm wat ik niet verwacht. Werkpakket is open, heb je interesse... etc. Volgens mij wil de aanmaker van het werkpakket niet inschrijven op zijn eigen werkpakket.
![Screenshot 2020-04-06 at 09 59 04](https://user-images.githubusercontent.com/11490452/78538308-11f03500-77f1-11ea-89ed-b242f16eda46.png)

**Comment by 0x029Ax0** [comment]
Ik kan me wel scenario's voorstellen waarin je dit wilt doen. Maar voor nu heb ik voor eigenaren van taken een nieuw scherm toegevoegd waarin wordt gevraagd te wachten (wanneer er open posities zijn) i.p.v. de vraag om jezelf in te schrijven. Vanavond online.
