### ISSUE TITLE
Project wijzigen - Niet alle velden editbaar

### ISSUE THREAD

**Issue by WinkoErades** [SSC-ICT-Innovatie/HNNW-project#65]
Bij het wijzigen van projecten kan ik niet alle velden zien / editten.

**Comment by WinkoErades** [comment]
Er ontbreken een aantal velden mijn inziens

**Comment by 0x029Ax0** [comment]
Welke dan? Zou je iets specifieker kunnen zijn?

**Comment by 0x029Ax0** [comment]
Bij edit minder velden dan create (werkpakketten en projecten).

**Comment by cookiemonster** [comment]
@VerheijenWebdevelopment Heb je nog meer (specifieke) informatie nodig? Want dan pas ik het label  aan. :-)
