### ISSUE TITLE
Projecten-wijzigen project andere eigenaar

### ISSUE THREAD

**Issue by ramonfiedler** [SSC-ICT-Innovatie/HNNW-project#69]
Moet ik wel in staat zijn om een project van iemand anders te wijzigen zonder toestemming ofwel een check?
<img width="408" alt="Schermafbeelding 2020-04-07 om 16 20 24" src="https://user-images.githubusercontent.com/42998678/78680498-db4b1500-78eb-11ea-9763-063f0b481b4a.png">

**Comment by 0x029Ax0** [comment]
Als je een admin account hebt, wat in jou geval zo is, dan wel ja.
