### ISSUE TITLE
Homepage: Content aanleveren: 3 images stories en voor het drieluik

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#7]
Locatie: <div id="homepage-quick-links">
Animatie [Pulse](https://daneden.github.io/animate.css/) op images met een mouse over.

**Comment by cookiemonster** [comment]
Werkzaamheden staan nu in [Trello](https://trello.com/c/nqB8Qjym/29-content)

**Comment by ramonfiedler** [comment]
De drieluik wilde je toch verwijderen op basis van de feedback van de tester(s) ?

**Comment by ramonfiedler** [comment]
Oh wacht .....ik zie nu dat je dat idd hebt gedaan
