### ISSUE TITLE
Home > Creation Splash > Design + Translation

### ISSUE THREAD

**Issue by 0x029Ax0** [SSC-ICT-Innovatie/HNNW-project#78]
Staat nu alleen nog de bare bones.

**Comment by 0x029Ax0** [comment]
@vgevers @WinkoErades Zouden jullie hier teksten voor kunnen aanleveren? Het gaat om de pagina: https://core.hnnw.nl/get-started

**Comment by cookiemonster** [comment]
https://beta.hnnw.nl/get-started is nog kaal.
