### ISSUE TITLE
Project: Uitbreiding voorbeeld tekst aan  "Projectomschrijving" veld

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#79]
1. Projectomschrijving inclusief doel 
2. Wat is het product dat je wil toetsen? 
3. Wat gaat je helpen? 
4. Wie is de doelgroep/ontvanger? 
5. Hoe de verbeteringen te meten?

**Comment by 0x029Ax0** [comment]
Staat online. Denk echter dat de tekst beter kan. Het hoeft niet altijd om een product te gaan en verbeteringen meten is ook lang niet altijd relevant. Denk dat we niks in het formulier moeten plaatsen wat niet generiek is; of het anders zo verwoorden dat het duidelijk is dat het geen vereiste is. Nu lopen we risico dat mensen verward raken omdat de geschetste verwachting niet overeenkomt met het project dat ze voor ogen hadden.
