### ISSUE TITLE
subscribe projecten en profiel status 

### ISSUE THREAD

**Issue by ramonfiedler** [SSC-ICT-Innovatie/HNNW-project#84]
wanneer ik een project subscription heb gedaan, zie ik dat niet terug bij " Huidige projecten"

**Comment by 0x029Ax0** [comment]
Nu zie je op je dashboard terug op welke entiteiten (gebruikers, projecten of werkpakketten (en later ministeries & organisaties)) je bent gesubscribed/je volgt.

De projecten onder "huidige projecten" zouden de projecten moeten zijn waar je onderdeel/teamlid van bent. Ik heb subtitles toegevoegd op je dashboard om duidelijk te maken wat er precies wordt aangegeven. Idee is om dit ook op je profiel te doen zodat misverstanden worden voorkomen.

Als je het eens bent me oplossing graag sluiten!

**Comment by 0x029Ax0** [comment]
Zelf maar geclosed..
