### ISSUE TITLE
Admin: User management

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#89]
Gebruikers
*  Zoeken
*  Stuur een bericht
*  Wijzigen 
  * Bewerken 
   * Naam
   * E-mailadres (nooit onzichtbaar voor de beheerders)	
   * E-mailadres activaties status (Niet geactiveerd, geactiveerd)
   * Telefoon nummer
   * Wachtwoord
* Verwijderen

**Comment by 0x029Ax0** [comment]
Zit er al in op "stuur een bericht" na. Zal ik morgen toevoegen.
