### ISSUE TITLE
Feedback Simone Koppius Transitie

### ISSUE THREAD

**Issue by 0x029Ax0** [SSC-ICT-Innovatie/HNNW-project#90]
1) Ik zoek op “den haag”. Daaruit krijg ik 2 resultaten: Organisatie (CIBG) en Gebruiker (Winko van den Berg). Ik kan w’el doorklikken op Gebruiker, niet op Organisatie

2) Ik maak een werkpakket aan. Als ik bij “vereiste vaardigheden” aanmaak, dan is het niet duidelijk wat ik op het 3e vakje moet invullen. Een toelichitng?
3) Opmerking: zou je bij werkpakkeet ook een tijdsperiode aan willen geven ? wanneer het werk uitgevoerd moet worden?
4) Op de homepage linken de plaatjes “ zo haal je meer uit je werk” “ tips uitleg en inspiratie” en “ meedoen als vrijwilliger” en “ meld je project aan” en alle “ veelgestelde vragen” en alle links onderaan de pagina (HNNW, voor medewerkers etc) nog niet naar een pagina
5) Opmerking: waarom zijn projecten en werkpakketten 2 verschllende pagina’s? met andere filters? Dat is voor mij niet duidelijk
6) Opmerking: zou je dashboard en profiel niet met elkaar integreren? Ik kom er op omdat Reviews en Notificaties op beide pagina’s terugkomen
7) Van Community ga ik naar Organisatie naar SSC-ICT . Daar zie ik de departementen Innovatie en Mobile Development. Klopt het dat ik daar nog niet op kan klikekn? Ik zou hier ook alle werkpakketten en projecten van SSC-ICT verwachten

😎 Opmerking: zou je bij community ook niet juist horizontale verbanden , onafhankelijk van organisatie, willen hebben? Vakgebieden zoals Java, MySQL, Lean….

**Comment by 0x029Ax0** [comment]
1. ✔️
2. ✔️
3. ✔️
4. Hier kan ik niks mee doen tot de statische pagina's zijn bedacht, nu staan er alleen dummy pagina's.
5. Omdat het aparte entiteiten zijn en die niet samen te voegen zijn per definitie. De overzichten zouden eventueel wel kunnen worden samengevoegd. Hier moet eerst over worden gebrainstormd.
6. Ook dit zijn aparte dingen en de overeenkomsten verantwoorden een samenvoeging niet.
7. ✔️
7. b. Projecten en werkpakketten tonen onder ministeries, organisaties en departementen is toegevoegd aan de to-do list en zal spoedig worden toegevoegd.
8. Lijkt mij slim om na te denken over hoe we alle overzichten het beste kunnen weergeven, ook hier moet over worden gebrainstormd.

**Comment by ramonfiedler** [comment]
Hi @VerheijenWebdevelopment Hoe lukt het met het oplossen / doorvoeren van deze 7 issues?

**Comment by 0x029Ax0** [comment]
> 
> 
> Hi @VerheijenWebdevelopment Hoe lukt het met het oplossen / doorvoeren van deze 7 issues?

Hey ramon, heb mijn bovenstaande comment aangepast om de huidige staat van de ticket beter weer te geven.

**Comment by 0x029Ax0** [comment]
8. ✔️ - Ministeries, organisaties & departementen hebben een eigen pagina met daarin een overzicht van projecten & werkpakketten.

**Comment by ramonfiedler** [comment]
top, dank voor de feedback. En idd uiteindelijk bepaal jij samen met Victor de prio's

**Comment by cookiemonster** [comment]
4. "Op de homepage linken de plaatjes “ zo haal je meer uit je werk” “ tips uitleg en inspiratie” en “ meedoen als vrijwilliger” en “ meld je project aan” en alle “ veelgestelde vragen” en alle links onderaan de pagina (HNNW, voor medewerkers etc) nog niet naar een pagina. "

Hier zijn aparte issues #9 #10 en #11 voor gemaakt die opgepakt moeten worden door het [content team](https://github.com/SSC-ICT-Innovatie/HNNW-project/issues?q=is%3Aissue+is%3Aopen+label%3A%22content+team%22)
