### ISSUE TITLE
Rijkshuisstijl: Rijksoverheid MinBZK logo plaatsen

### ISSUE THREAD

**Issue by cookiemonster** [SSC-ICT-Innovatie/HNNW-project#91]
Rijksoverheidslogo plaatsen in boven in het scherm in het midden.
Bron: https://www.rijkshuisstijl.nl/logos

**Comment by 0x029Ax0** [comment]
De homepage bevat nu het rijksoverheid logo wanneer de gebruiker niet is ingelogd. Wanneer de gebruiker wel is ingelogd of zich op een andere pagina bevindt is het logo niet zichtbaar wegens gebrek aan ruimte.

In design 2.0 hier wellicht een oplossing voor zoeken indien nodig. Voor nu fixed & closed.

**Comment by 0x029Ax0** [comment]
De homepage bevat nu het rijksoverheid logo wanneer de gebruiker niet is ingelogd. Wanneer de gebruiker wel is ingelogd of zich op een andere pagina bevindt is het logo niet zichtbaar wegens gebrek aan ruimte.

In design 2.0 hier wellicht een oplossing voor zoeken indien nodig. Voor nu fixed & closed.
